### PR TITLE
Fixed port parameter passed with an intent, fixes #80

### LINKED ISSUE #80: Cannot connect with an intent using a secure connection
I run into a bug while sending an intent to aSpice.

Description:
aSpice cannot connect when using a secure connection.
the app (moVirt) is sending intent similar to this one:
spice://10.34.62.41:-1?SpicePassword=password&TlsPort=5910&CertSubject=subject&CaCertPath=/path/to/ca.crt

The problem is that aSpice doesn't interpret port as -1, but leaves default port 5900 and fails to connect. Other boundary values other than -1 don't help either.

The only problematic part is I think in ConnectionBean.java

on line 102 
https://github.com/iiordanov/remote-desktop-clients/blob/master/eclipse_projects/bVNC/src/com/iiordanov/bVNC/ConnectionBean.java#L102

and line 294
https://github.com/iiordanov/remote-desktop-clients/blob/master/eclipse_projects/bVNC/src/com/iiordanov/bVNC/ConnectionBean.java#L294

where the port isn't set if we receive -1 from the intent and DEFAULT_VNC_PORT 5900 is used instead

### PR DESCRIPTION
**Pull request by suomiy**
I am sorry, I didn't test it.

alternative fix:
we could setPort(-1); on line 102

### CODE REVIEW

File: eclipse_projects/bVNC/src/com/iiordanov/bVNC/ConnectionBean.java [hunk 1]
```diff
@@ -291,11 +291,10 @@ void parseFromUri(Uri dataUri) {
...
     	final int PORT_NONE = -1;
         int port = dataUri.getPort();
-        if (port != PORT_NONE) {
-        	if (!isValidPort(port))
-        		throw new IllegalArgumentException("The specified VNC port is not valid.");
-        	setPort(port);
+        if (port != PORT_NONE && !isValidPort(port)) {
+        	throw new IllegalArgumentException("The specified VNC port is not valid.");
         }
+        setPort(port);
```
Comment (suomiy) [inline eclipse_projects/bVNC/src/com/iiordanov/bVNC/ConnectionBean.java]: not sure if we should do something if we receive port and TLS both as -1
